name: Deploy to GitHub Pages

# Exécute le workflow lorsque des changements sont poussés sur la branche main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le code source de la branche `main`
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      # 3. Installation des dépendances
      - name: Install dependencies
        run: npm install

      # 4. Générer le site statique
      - name: Build project
        run: npm run generate

      # 5. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le token GitHub pour authentifier le déploiement
          publish_dir: ./dist  # Le dossier où Nuxt génère les fichiers statiques
